global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "mlops-monitor"
    project: "imdb-rating-prediction"

# Rule files for alerting
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    metrics_path: /metrics
    scrape_interval: 30s

  # MLOps API metrics
  - job_name: "mlops-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ["prometheus"]

  # MLflow Prometheus metrics (from your Python script)
  - job_name: "mlflow-metrics"
    static_configs:
      - targets: ["mlflow:9090"] # Internal container port
    metrics_path: /metrics
    scrape_interval: 30s

  # System metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s

  # Container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s

  # Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: /metrics
    scrape_interval: 30s
