# .github/workflows/section5-docker-test.yml
name: Section 5 - Docker Containerization Test

on:
  push:
    branches: [main, develop]
    paths:
      - "docker/**"
      - "src/api/**"
      - "requirements*.txt"
  pull_request:
    branches: [main]
    paths:
      - "docker/**"
      - "src/api/**"
      - "requirements*.txt"

jobs:
  docker-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-resolved.txt

      - name: Validate Docker Compose files
        run: |
          # No installation needed - use built-in Docker Compose V2
          docker compose --version
          # Validate compose files
          docker compose -f docker/docker-compose.yml config --quiet
          docker compose -f docker/docker-compose.prod.yml config --quiet
          echo "✅ Docker Compose files are valid"

      - name: Build Docker images
        run: |
          # Build API image
          docker build -f docker/Dockerfile.api -t mlops-imdb-api:test .

          # Build training image
          docker build -f docker/Dockerfile.train -t mlops-imdb-trainer:test .

          echo "✅ Docker images built successfully"

      - name: Run simulation tests
        run: |
          python scripts/tests/section5_simulation_test.py

      - name: Prepare test model
        run: |
          # Create necessary directories
          mkdir -p models data/processed
          
          # Create a simple test model for the API
          python -c "
          import joblib
          import numpy as np
          from sklearn.ensemble import RandomForestRegressor
          from sklearn.preprocessing import StandardScaler
          
          # Create a simple model
          model = RandomForestRegressor(n_estimators=10, random_state=42)
          X = np.random.rand(100, 3)  # 3 features: startYear, runtimeMinutes, numVotes
          y = np.random.rand(100) * 10  # ratings 0-10
          model.fit(X, y)
          
          # Create scaler
          scaler = StandardScaler()
          scaler.fit(X)
          
          # Save model data in expected format
          model_data = {
              'model': model,
              'scaler': scaler,
              'feature_names': ['startYear', 'runtimeMinutes', 'numVotes'],
              'model_info': {
                  'model_type': 'RandomForestRegressor',
                  'features': 3,
                  'version': '1.0.0'
              }
          }
          joblib.dump(model_data, 'models/latest_model.joblib')
          print('✅ Test model created for CI/CD')
          "
          
      - name: Test Docker containers
        run: |
          # Start services
          cd docker
          docker compose up -d

          # Wait for services
          sleep 30

          # Test API health
          curl -f http://localhost:8000/health || exit 1

          # Test MLflow health
          curl -f http://localhost:5000/health || exit 1

          # Test prediction endpoint
          curl -X POST "http://localhost:8000/predict/movie" \
               -H "Content-Type: application/json" \
               -d '{"title":"Test Movie","startYear":2020,"runtimeMinutes":120,"numVotes":5000}' \
               || exit 1

          echo "✅ Container tests passed"

      - name: Cleanup
        if: always()
        run: |
          cd docker
          docker compose down --volumes --remove-orphans

  enhanced-features-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install enhanced dependencies
        run: |
          python -m pip install --upgrade pip
          pip install icecream tqdm fire rich

      - name: Test enhanced utilities
        run: |
          python -c "
          from src.utils.enhanced import EnhancedLogger, display_table, demo_enhanced_features
          logger = EnhancedLogger('CI/CD')
          logger.success('Enhanced utilities working in CI/CD!')
          demo_enhanced_features()
          "

      - name: Test enhanced CLI
        run: |
          python src/utils/enhanced.py test_imports
          python src/utils/enhanced.py demo_enhanced_features

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "./docker"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install -r requirements-resolved.txt # ✅ Exact versions
          pip install pytest pytest-benchmark

      - name: Create dummy model for testing
        run: |
          mkdir -p models data/processed
          python -c "
          import joblib
          from sklearn.ensemble import RandomForestRegressor
          import numpy as np

          # Create dummy model
          model = RandomForestRegressor(n_estimators=10, random_state=42)
          X_dummy = np.random.random((100, 3))
          y_dummy = np.random.random(100) * 9 + 1
          model.fit(X_dummy, y_dummy)

          # Save model info
          model_info = {
              'model': model,
              'feature_names': ['startYear', 'runtimeMinutes', 'numVotes'],
              'model_type': 'RandomForestRegressor',
              'timestamp': '20250601_120000',
              'enhanced': True,
              'version': '2.0'
          }

          joblib.dump(model_info, 'models/test_model.joblib')
          print('✅ Dummy model created')
          "

      - name: Performance benchmark
        run: |
          python -c "
          import time
          import requests
          import subprocess
          import sys

          # Start API in background
          proc = subprocess.Popen([
              sys.executable, '-m', 'uvicorn',
              'src.api.main:app', '--host', '0.0.0.0', '--port', '8000'
          ])

          time.sleep(10)  # Wait for startup

          try:
              # Benchmark API response times
              times = []
              for i in range(10):
                  start = time.time()
                  response = requests.get('http://localhost:8000/health', timeout=5)
                  end = time.time()
                  if response.status_code == 200:
                      times.append(end - start)

              if times:
                  avg_time = sum(times) / len(times)
                  print(f'✅ Average API response time: {avg_time:.3f}s')

                  # Performance threshold
                  if avg_time > 1.0:
                      print('⚠️ API response time exceeds 1 second')
                      sys.exit(1)
              else:
                  print('❌ No successful API calls')
                  sys.exit(1)

          finally:
              proc.terminate()
              proc.wait()
          "

  documentation-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check documentation completeness
        run: |
          echo "📚 Checking Section 5 documentation..."

          # Check if essential documentation exists
          DOCS=(
            "docs/guide/Section5_instructions.md"
            "docs/guide/quick_reference.md"
            "README.md"
          )

          for doc in "${DOCS[@]}"; do
            if [ -f "$doc" ]; then
              echo "✅ $doc exists"
            else
              echo "❌ $doc missing"
              exit 1
            fi
          done

          # Check if Docker files have comments
          for dockerfile in docker/Dockerfile.api docker/Dockerfile.train; do
            if grep -q "^#" "$dockerfile"; then
              echo "✅ $dockerfile has documentation comments"
            else
              echo "⚠️ $dockerfile lacks documentation comments"
            fi
          done

          echo "✅ Documentation check passed"

  integration-test:
    runs-on: ubuntu-latest
    needs: [docker-validation, enhanced-features-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          # pip install -r requirements-enhanced.txt
          pip install -r requirements-resolved.txt # ✅ Exact versions

      - name: Create test data
        run: |
          mkdir -p data/processed
          python -c "
          import pandas as pd
          import numpy as np

          # Create minimal test dataset
          np.random.seed(42)
          n_movies = 1000

          df = pd.DataFrame({
              'tconst': [f'tt{i:07d}' for i in range(n_movies)],
              'primaryTitle': [f'Movie {i}' for i in range(n_movies)],
              'startYear': np.random.randint(1990, 2024, n_movies),
              'runtimeMinutes': np.random.randint(80, 180, n_movies),
              'numVotes': np.random.randint(100, 100000, n_movies),
              'averageRating': np.random.uniform(1.0, 10.0, n_movies),
              'genres': ['Drama,Action'] * n_movies
          })

          df.to_csv('data/processed/movies_with_ratings.csv', index=False)
          print('✅ Test dataset created')
          "

      - name: Run full integration test
        run: |
          # Test complete pipeline
          python -c "
          from src.models.trainer import run_training_pipeline

          # Run training with test data
          try:
              model_info = run_training_pipeline()
              print('✅ Training pipeline completed')
              print(f'Model saved: {model_info[\"model_path\"]}')
          except Exception as e:
              print(f'❌ Training pipeline failed: {e}')
              raise
          "

      - name: Test Docker deployment with real model
        run: |
          # Start full stack
          cd docker
          docker compose up -d
          sleep 45  # Wait for everything to be ready

          # Test with real prediction
          response=$(curl -s -X POST "http://localhost:8000/predict/movie" \
                          -H "Content-Type: application/json" \
                          -d '{"title":"Integration Test Movie","startYear":2020,"runtimeMinutes":120,"numVotes":5000}')

          echo "API Response: $response"

          # Check if response contains prediction
          if echo "$response" | grep -q "predicted_rating"; then
              echo "✅ Integration test passed"
          else
              echo "❌ Integration test failed"
              exit 1
          fi

          # Cleanup
          docker compose down --volumes --remove-orphans

      - name: Generate test report
        if: always()
        run: |
          python -c "
          import json
          from datetime import datetime

          report = {
              'test_date': datetime.now().isoformat(),
              'section': 'Section 5 - Docker Containerization',
              'environment': 'GitHub Actions CI/CD',
              'tests_completed': [
                  'Docker validation',
                  'Enhanced features test',
                  'Security scan',
                  'Performance benchmark',
                  'Documentation check',
                  'Integration test'
              ],
              'status': 'PASSED',
              'next_section': 'Section 6 - Monitoring & CI/CD'
          }

          with open('section5_ci_test_report.json', 'w') as f:
              json.dump(report, f, indent=2)

          print('✅ Test report generated')
          "

      - name: Upload test artifacts
        uses: codecov/codecov-action@v4
        if: always()
        with:
          name: section5-test-results
          path: |
            section5_ci_test_report.json
            models/
            logs/
          retention-days: 30
